#### Ángel Martínez

# S02 T02 Estructura de una Matriz

## Nivel 1

### Exercici 1

#### Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [54]:
import numpy as np

In [55]:
A = np.array([1000000000, 7000000000, 4000000000, 5000000000, 8000000000, 9000000000, 7000000000, 6000000000])

In [56]:
print(A)

[1000000000 7000000000 4000000000 5000000000 8000000000 9000000000
 7000000000 6000000000]


In [57]:
A.dtype

dtype('int64')

In [58]:
print("La dimensión de la matriz 'A' es:", A.ndim)

La dimensión de la matriz 'A' es: 1


In [59]:
print("La forma de la matriz 'A' es:", A.shape)

La forma de la matriz 'A' es: (8,)


### Exercici 2

#### De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.

In [60]:
media_A = np.mean(A)
print("La media del Array 'A' es:", media_A)

La media del Array 'A' es: 5875000000.0


### Exercici 3

#### Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [61]:
print("La matriz B es la siguiente")
B = np.random.randint(0, 100, (5,5))
print()
print(B)
print()
print("Las dimensiones de la matriz B son:", B.ndim)

La matriz B es la siguiente

[[29 42 17  2 10]
 [ 4 87  9 14 42]
 [ 2 40 76 94 36]
 [43  6 26 74 81]
 [17 37 52 98 73]]

Las dimensiones de la matriz B son: 2


In [62]:
#Extraer el valor máximo de la matriz completa

max_value = np.max(B)
print("El valor máximo de la matriz completa es:", max_value)
print()

#Extraer el valor máximo de cada una de las filas

print("Los valores máximos de cada fila son:")
print()

numFila = 1

for max_value_row in np.max(B, axis=1):
    print("En la fila", numFila, ":", max_value_row)
    numFila += 1

#Extraer el valor máximo de cada una de las columnas

print()
print("Los valores máximos de cada columna son:")
print()

numColumna = 1

for max_value_column in np.max(B, axis=0):
    print("En la columna", numColumna, ":", max_value_column)
    numColumna += 1

El valor máximo de la matriz completa es: 98

Los valores máximos de cada fila son:

En la fila 1 : 42
En la fila 2 : 87
En la fila 3 : 94
En la fila 4 : 81
En la fila 5 : 98

Los valores máximos de cada columna son:

En la columna 1 : 43
En la columna 2 : 87
En la columna 3 : 76
En la columna 4 : 98
En la columna 5 : 81
